FROM vllm/vllm-openai:v0.11.2

RUN apt-get update && \
    apt-get install -y \
        fonts-noto-core \
        fonts-noto-cjk \
        fontconfig \
        libgl1 && \
    fc-cache -fv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/MinerU
COPY . /opt/MinerU

RUN python3 -m pip install -U pip --break-system-packages && \
    python3 -m pip install -e '.[core]' --break-system-packages && \
    python3 -m pip cache purge

RUN mineru-models-download -s huggingface -m all

ENTRYPOINT ["/bin/bash", "-c", "export MINERU_MODEL_SOURCE=local && exec \"$@\"", "--"]
