# Use DaoCloud mirrored vllm image for China region for gpu with Volta、Turing、Ampere、Ada Lovelace、Hopper、Blackwell architecture (7.0 <= Compute Capability <= 12.0)
# Compute Capability version query (https://developer.nvidia.com/cuda-gpus)
# support x86_64 architecture and ARM(AArch64) architecture
FROM docker.m.daocloud.io/vllm/vllm-openai:v0.11.2

WORKDIR /opt/MinerU
COPY . /opt/MinerU

RUN python3 -m pip install -U pip -i https://mirrors.aliyun.com/pypi/simple --break-system-packages && \
    python3 -m pip install -e '.[core]' -i https://mirrors.aliyun.com/pypi/simple --break-system-packages && \
    python3 -m pip cache purge

ENTRYPOINT ["/bin/bash", "-c", "export MINERU_MODEL_SOURCE=${MINERU_MODEL_SOURCE:-modelscope} && exec \"$@\"", "--"]
